language: node_js
node_js:
  - "10"

before_script:
  - npm install
  - npm rebuild

script:
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true